"""Ingestion: populate the local SQL database.

Source priority (hybrid, per user decision):
  1. Key-less IMD sources when ENABLE_LIVE_IMD=true (observation scrape,
     legacy district warnings/forecast) -> stored with is_demo=0.
  2. The deterministic simulator for everything that is not reachable -> stored
     with is_demo=1 and source='simulated'.

Every row carries provenance (`source`, `is_demo`) so the UI can label
demonstration data and never present it as real-time weather.

AQI: IMD's public key-less endpoints do not expose AQI, so AQI rows are always
generated by the labelled simulator (is_demo=1, source='simulated-aqi'). They are
NEVER presented as official measurements.
"""
import asyncio
import hashlib
import json
from datetime import datetime, timedelta, timezone

from . import config, imd_client, simulator
from .db import execute, executemany, query_one
from .stations import STATIONS


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat()


def _hash_int(*parts) -> int:
    h = hashlib.sha256("|".join(str(p) for p in parts).encode()).hexdigest()
    return int(h[:12], 16)


def set_meta(key: str, value) -> None:
    execute(
        "INSERT INTO dataset_meta(key, value) VALUES(?, ?) "
        "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
        (key, json.dumps(value)),
    )


def get_meta(key: str, default=None):
    row = query_one("SELECT value FROM dataset_meta WHERE key=?", (key,))
    if not row:
        return default
    try:
        return json.loads(row["value"])
    except (ValueError, TypeError):
        return row["value"]


def seed_locations() -> None:
    rows = [
        (
            s["id"], s["name"], s["state"], s["lat"], s["lon"],
            s.get("station_id"), s.get("forecast_id"), s.get("radar_code"),
            s.get("site_slug"), s.get("district"),
        )
        for s in STATIONS
    ]
    executemany(
        "INSERT INTO locations(id,name,state,lat,lon,station_id,forecast_id,radar_code,site_slug,district) "
        "VALUES(?,?,?,?,?,?,?,?,?,?) "
        "ON CONFLICT(id) DO UPDATE SET name=excluded.name, state=excluded.state, lat=excluded.lat, "
        "lon=excluded.lon, station_id=excluded.station_id, forecast_id=excluded.forecast_id, "
        "radar_code=excluded.radar_code, site_slug=excluded.site_slug, district=excluded.district",
        rows,
    )


def aqi_category(aqi: float) -> str:
    if aqi <= 50:
        return "Good"
    if aqi <= 100:
        return "Satisfactory"
    if aqi <= 200:
        return "Moderate"
    if aqi <= 300:
        return "Poor"
    if aqi <= 400:
        return "Very Poor"
    return "Severe"


def _sim_aqi(location_id: str, dt: datetime) -> dict:
    base = 40 + (_hash_int(location_id, "aqi") % 120)
    seasonal = 25 * (1 if dt.month in (11, 12, 1) else 0)
    jitter = (_hash_int(location_id, dt.strftime("%Y%m%d")) % 60) - 30
    aqi = max(15, min(430, base + seasonal + jitter))
    pm25 = round(aqi * 0.55, 1)
    pm10 = round(aqi * 0.9, 1)
    return {
        "aqi": round(aqi),
        "category": aqi_category(aqi),
        "pm25": pm25,
        "pm10": pm10,
        "no2": round(aqi * 0.12, 1),
        "so2": round(aqi * 0.06, 1),
        "co": round(aqi * 0.02, 2),
        "o3": round(aqi * 0.18, 1),
    }


async def _live_current(station):
    if not config.is_live_enabled():
        return None
    try:
        res = await imd_client.get_observation(station)
        return res.get("data") if res.get("ok") else None
    except Exception:
        return None


async def _live_forecast(station):
    if not config.is_live_enabled():
        return None
    try:
        res = await imd_client.get_forecast(station)
        return res.get("data") if res.get("ok") else None
    except Exception:
        return None


async def _live_warnings(station):
    if not config.is_live_enabled():
        return None
    try:
        res = await imd_client.get_district_warnings(station)
        return res.get("data") if res.get("ok") else None
    except Exception:
        return None


async def ingest_location(station, history_days: int = 30) -> dict:
    now = _now()
    loc = station["id"]
    created = _iso(now)
    live_obs_used = False
    live_fc_used = False

    # ---- Observations: 30-day daily backfill (labelled) + latest ----
    obs_rows = []
    for i in range(history_days, 0, -1):
        day = now - timedelta(days=i)
        sim = simulator.simulate_current(loc, now=day.replace(hour=14, minute=0, second=0, microsecond=0))
        obs_rows.append(_obs_tuple(loc, sim, day.isoformat(), "simulated", 1, created))

    current = await _live_current(station)
    if current:
        live_obs_used = True
        obs_rows.append(_obs_tuple_from_parsed(loc, current, _iso(now), "imd-scrape", 0, created))
    else:
        sim = simulator.simulate_current(loc, now=now)
        obs_rows.append(_obs_tuple(loc, sim, _iso(now), "simulated", 1, created))

    execute("DELETE FROM observations WHERE location_id=?", (loc,))
    executemany(
        "INSERT INTO observations(location_id,observed_at,temperature,feels_like,humidity,wind_speed,"
        "wind_direction,pressure,visibility,rainfall,weather_condition,station_name,source,is_demo,created_at) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        obs_rows,
    )

    # ---- Forecast (next 7 days) ----
    fc = await _live_forecast(station)
    fc_source, fc_demo = ("imd-legacy", 0) if fc else ("simulated", 1)
    live_fc_used = bool(fc)
    if not fc:
        fc = simulator.simulate_forecast(loc, 7, now=now)
    fc_rows = [
        (
            loc, d.get("date"), d.get("weekday"), d.get("tMin"), d.get("tMax"), d.get("condition"),
            d.get("rainProb"), d.get("rainfall"), d.get("humidity"), d.get("windSpeed"),
            fc_source, fc_demo, created,
        )
        for d in fc
    ]
    execute("DELETE FROM forecast WHERE location_id=?", (loc,))
    executemany(
        "INSERT INTO forecast(location_id,forecast_date,weekday,tmin,tmax,condition,rain_prob,rainfall,"
        "humidity,wind_speed,source,is_demo,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
        fc_rows,
    )

    # ---- Hourly (next 24h) ----
    hourly = simulator.simulate_hourly(loc, now=now)
    h_rows = [
        (loc, h.get("time"), h.get("label"), h.get("temperature"), h.get("rainProb"), h.get("humidity"),
         "simulated", 1, created)
        for h in hourly
    ]
    execute("DELETE FROM hourly WHERE location_id=?", (loc,))
    executemany(
        "INSERT INTO hourly(location_id,ts,label,temperature,rain_prob,humidity,source,is_demo,created_at) "
        "VALUES(?,?,?,?,?,?,?,?,?)",
        h_rows,
    )

    # ---- Alerts ----
    warns = await _live_warnings(station)
    w_source, w_demo = ("imd-legacy", 0) if warns else ("simulated", 1)
    if not warns:
        warns = simulator.simulate_warnings(loc, now=now)
    a_rows = [
        (
            loc, w.get("severity", "no_warning"), w.get("event"), w.get("detail") or w.get("description") or "",
            w.get("area") or station["district"], w.get("validFrom"), w.get("validUntil"),
            _instructions_for(w.get("severity", "no_warning")), w_source, w_demo, created,
        )
        for w in warns
    ]
    execute("DELETE FROM alerts WHERE location_id=?", (loc,))
    if a_rows:
        executemany(
            "INSERT INTO alerts(location_id,severity,event,description,area,valid_from,valid_until,"
            "instructions,source,is_demo,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",
            a_rows,
        )

    # ---- AQI (labelled demo — no key-less AQI source available) ----
    aqi_rows = []
    for i in range(history_days, -1, -1):
        day = now - timedelta(days=i)
        vals = _sim_aqi(loc, day)
        aqi_rows.append(
            (
                loc, day.isoformat(), vals["aqi"], vals["category"], vals["pm25"], vals["pm10"], vals["no2"],
                vals["so2"], vals["co"], vals["o3"], "simulated-aqi", 1, created,
            )
        )
    execute("DELETE FROM aqi WHERE location_id=?", (loc,))
    executemany(
        "INSERT INTO aqi(location_id,recorded_at,aqi,category,pm25,pm10,no2,so2,co,o3,source,is_demo,created_at) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
        aqi_rows,
    )

    return {"location": loc, "live_observation": live_obs_used, "live_forecast": live_fc_used}


def _obs_tuple(loc, sim, observed_at, source, is_demo, created):
    return (
        loc, observed_at, sim.get("temperature"), sim.get("feelsLike"), sim.get("humidity"),
        sim.get("windSpeed"), sim.get("windDirection"), sim.get("pressure"), sim.get("visibility"),
        sim.get("rainfall"), sim.get("weatherCondition"), sim.get("stationName") or sim.get("location"),
        source, is_demo, created,
    )


def _obs_tuple_from_parsed(loc, cur, observed_at, source, is_demo, created):
    return (
        loc, cur.get("observedAt") or observed_at, cur.get("temperature"), cur.get("feelsLike"),
        cur.get("humidity"), cur.get("windSpeed"), cur.get("windDirection"), cur.get("pressure"),
        cur.get("visibility"), cur.get("rainfall"), cur.get("weatherCondition"), cur.get("stationName"),
        source, is_demo, created,
    )


def _instructions_for(severity: str) -> str:
    return {
        "warning": "Avoid non-essential travel; follow district administration and IMD advisories.",
        "alert": "Be prepared; secure loose outdoor objects and monitor official updates.",
        "watch": "Stay informed; weather conditions may change over the next few hours.",
        "no_warning": "No specific action required.",
    }.get(severity or "no_warning", "Follow official advisories.")


async def ingest_all(force: bool = False) -> dict:
    """Ingest every location. Safe to call at startup and from an admin endpoint."""
    from .db import init_db

    init_db()
    seed_locations()
    results = await asyncio.gather(
        *[ingest_location(s) for s in STATIONS], return_exceptions=True
    )
    ok = [r for r in results if isinstance(r, dict)]
    live_count = sum(1 for r in ok if r.get("live_observation"))
    set_meta("last_ingest_at", _iso(_now()))
    set_meta("source_mode", "live" if config.is_live_enabled() else "simulated")
    set_meta("live_locations", live_count)
    set_meta("locations_ingested", len(ok))
    return {"ok": True, "locations": len(ok), "liveObservations": live_count,
            "sourceMode": "live" if config.is_live_enabled() else "simulated"}


def is_seeded() -> bool:
    row = query_one("SELECT COUNT(*) AS c FROM observations")
    return bool(row and row["c"] > 0)